openimsdk/protocol

- auth/auth.go
- conversation/conversation.go
- friend/friend.go
- group/group.go
- msg/msg.go
- push/push.go
- user/user.go
> Add parameter verification of req for each rpc request and Replaced with the errors of the go standard library

- constant/limit.go
- user/user.go
> Get user online status plus limit

- constant/constant.go
> add UserStatusChangeNotification constant

- msg/msg.proto
> feat:add get server time protocol

- LICENSE
Add Apache license file explicitly
<br>
/kind documentation
Fixes #28
> Add Apache LICENSE

- conversation/conversation.go
> feat: add args check to support set conversation.

- constant/constant.go
> add:add one constant value

- msg/msg.go
> fix: del the searchMessage Check

- constant/constant.go
> fix: add a IMOrdinaryUser

- group/group.go
Fixes #
fix:only one can create group
I have read the CLA Document and I hereby sign the CLA
> fix:only one can create group

- user/user.go
Fixes # open-im-server #2310
no faceURL error return
> fix:no faceURL error return

- user/user.go
- util/datautil/string.go
> Fix user id check

- constant/group.go
- group/group.go
> feature: check

- user/user.go
> fix: check user id

- conversation/conversation.go
- group/group.go
- msg/msg.go
- user/user.go
feat:implement rpc format method
> feat:implement rpc format method

- conversation/conversation.go
- group/group.go
- msg/msg.go
- relation/relation.go
- user/user.go
implement format method in pb.
> implement format method in pb.

- sdkws/sdkws.go
feat: update max Seq format method.
> feat: update max Seq format method.

- conversation/conversation.go
- group/group.go
- relation/relation.go
- sdkws/sdkws.go
- user/user.go
> update Format method in pb.

- sdkws/sdkws.go
Fixes [#2498](https://github.com/openimsdk/open-im-server/issues/2498)
fix: notification msg type check
> fix: notification msg type check

- user/user.go
Fixes #
feat: change GetUserStatus userIDs limit
> feat: change GetUserStatus userIDs limit

- constant/constant.go
> feat: login policy

- constant/platform_id_to_name.go
> feat: platform class

- gen.cmd
- gen.sh
- gen_openmeeting.sh
> fix: solve grpc generate.

- rpccall/caller.go
> feat: gen rpc

- rpccall/caller.go
> fix: gen proto

- magefile.go
> fix: magefile typo

- mage-README.md
> docs: remove unused type.

- user/user.go
> fix: system account check

- constant/platform_id_to_name.go
> feat: harmonyOS

- user/user.go
> fix: add updateUserInfoEx Check.

- auth/auth.pb.go
- auth/auth.proto
> update GetExistingToken parameter.

- constant/constant.go
- sdkws/sdkws.pb.go
- sdkws/sdkws.proto
> feat: add ConversationDeleteTips.
